rep: "Rep Name"
name: RegionGR

# Input Parameters
path: region_gr
data_date: 2024-11-20

# Time Parameters
timeunits2hour: 0.25
timeunits2minutes: 15

# Output Parameters
output_path: "output"

# Map Parameters
territory_center: {'lat':39.6417, 'lon':22.4167}

### Optimization Parameters
run_time_limit: 1
# Time Windows
allow_waiting_time: 24
max_time_units_per_day: 52
base_min_start: 0
window_max_time: 100
# Objective Weights
miss_appointment_penalty: 6 # set to 1 to ignore appointment misses
global_span_cost: 1 # coeff * (max_end - min_start) - Higher value reduces weekly span